title: <p align="center"> Triasto Adhinugroho </p> # your name (or website title) here
logo: "/images/photo.jpg?raw=true" # your photo (or logo) here
description:
  <p align="center">
  <a href="pdf/Triasto Adhinugroho resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/triasto-adhinugroho/">LinkedIn</a> 
  </p>
  
  <p align="justify">
  I am currently learning Data Scientist at Pacmann Academy Bootcamp.
  <br><br>
  I have passion to extract insights from large data sets and visualize them in a meaningful story.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 #
